### ISSUE TITLE
Errors when compiling production bundle [iOS]

### ISSUE THREAD

**Issue by cwbutler** [magicismight/react-native-svg#87]
I can run my project with the ios simulator and everything works great.

When I try to compile my app for production using this library I get a transform error when trying to bundle my js.

Command:

> react-native bundle --dev false --entry-file index.ios.js --bundle-output ios/main.jsbundle --platform ios

Error:

> /.../.../unity-mixer/node_modules/promise/lib/done.js:10
      throw err;
      ^
TypeError: /.../.../unity-mixer/node_modules/react-native-svg/elements/Path.js: Property object of JSXMemberExpression expected node to be of a type ["JSXMemberExpression","JSXIdentifier"] but instead got "MemberExpression"
    at Object.validate (/.../.../unity-mixer/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/.../.../unity-mixer/node_modules/babel-types/lib/index.js:541:9)
    at NodePath._replaceWith (/.../.../unity-mixer/node_modules/babel-core/node_modules/babel-traverse/lib/path/replacement.js:208:7)
    at NodePath.replaceWith (/.../.../unity-mixer/node_modules/babel-core/node_modules/babel-traverse/lib/path/replacement.js:186:8)
    at Object.ReferencedIdentifier (/.../.../unity-mixer/node_modules/babel-plugin-transform-es2015-modules-commonjs/lib/index.js:36:14)
    at Object.newFn (/.../.../unity-mixer/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:334:17)
    at NodePath._call (/.../.../unity-mixer/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/.../.../unity-mixer/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/.../.../unity-mixer/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:106:12)
TransformError: /.../.../unity-mixer/node_modules/react-native-svg/elements/Path.js: /.../.../unity-mixer/node_modules/react-native-svg/elements/Path.js: Property object of JSXMemberExpression expected node to be of a type ["JSXMemberExpression","JSXIdentifier"] but instead got "MemberExpression"

Using React Native 0.30.0

My project compiles fine when I do not require this project.

**Comment by cwbutler** [comment]
After hours of researching....

It seemed to be babel plugin I was using...  removed it and everything worked fine
[transform-react-constant-elements]

https://phabricator.babeljs.io/T6946

**Comment by lazarmarkov** [comment]
@cwbutler Saved me! Thank you friend!!
